version: '2'
services:
  web:
    image: drupal
    ports:
      - '8080:80'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: MyPassword
    volumes:
      - my-postgres-db:/var/lib/postgresql/data
volumes:
  my-postgres-db: