AWSTemplateFormatVersion: 2010-09-09
Description: EC2 boxes for docker swarm examples
Parameters:
  ImageId:
    Type: String
  SubnetId:
    Type: String
  SecurityGroupId:
    Type: String
  KeyName:
    Type: String
Resources:
  DockerBox:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t3.micro
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId:
        Fn::ImportValue: !Ref SubnetId
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install docker -y
            service docker start
            usermod -a -G docker ec2-user
            chkconfig docker on
            yum install -y git
            curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      KeyName: !Ref KeyName